import { FilterConfig } from '../types';

export const FILTERS: FilterConfig[] = [
  // ==================== 🌈 BASIC FILTERS ====================
  {
    id: 'original',
    name: 'Original',
    category: 'basic',
    cssFilter: 'none',
    previewGradient: 'linear-gradient(135deg, #64748b, #94a3b8)',
  },
  {
    id: 'bright',
    name: 'Bright',
    category: 'basic',
    cssFilter: 'brightness(1.2) contrast(1.05)',
    previewGradient: 'linear-gradient(135deg, #fef08a, #fde047)',
  },
  {
    id: 'contrast',
    name: 'Contrast',
    category: 'basic',
    cssFilter: 'contrast(1.35) saturate(1.1)',
    previewGradient: 'linear-gradient(135deg, #1e293b, #475569)',
  },
  {
    id: 'saturation',
    name: 'Saturation',
    category: 'basic',
    cssFilter: 'saturate(1.7) contrast(1.05)',
    previewGradient: 'linear-gradient(135deg, #f43f5e, #fb7185)',
  },
  {
    id: 'warm',
    name: 'Warm',
    category: 'basic',
    cssFilter: 'sepia(0.25) saturate(1.2) brightness(1.05) hue-rotate(-10deg)',
    overlayColor: 'rgba(251, 191, 36, 0.12)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #fbbf24, #f97316)',
  },
  {
    id: 'cool',
    name: 'Cool',
    category: 'basic',
    cssFilter: 'hue-rotate(15deg) saturate(1.1) brightness(1.02)',
    overlayColor: 'rgba(56, 189, 248, 0.12)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #38bdf8, #0284c7)',
  },
  {
    id: 'fade',
    name: 'Fade',
    category: 'basic',
    cssFilter: 'contrast(0.85) brightness(1.1) saturate(0.85)',
    previewGradient: 'linear-gradient(135deg, #cbd5e1, #94a3b8)',
  },
  {
    id: 'vibrant',
    name: 'Vibrant',
    category: 'basic',
    cssFilter: 'saturate(1.5) contrast(1.15) brightness(1.05)',
    previewGradient: 'linear-gradient(135deg, #ec4899, #8b5cf6)',
  },
  {
    id: 'soft',
    name: 'Soft',
    category: 'basic',
    cssFilter: 'brightness(1.08) contrast(0.92) saturate(1.05) blur(0.3px)',
    previewGradient: 'linear-gradient(135deg, #fbcfe8, #f472b6)',
  },
  {
    id: 'sharp',
    name: 'Sharp',
    category: 'basic',
    cssFilter: 'contrast(1.25) brightness(1.05) saturate(1.1)',
    previewGradient: 'linear-gradient(135deg, #0ea5e9, #0284c7)',
  },
  {
    id: 'matte',
    name: 'Matte',
    category: 'basic',
    cssFilter: 'contrast(0.9) brightness(1.05) saturate(0.9) sepia(0.1)',
    previewGradient: 'linear-gradient(135deg, #78716c, #a8a29e)',
  },
  {
    id: 'crisp',
    name: 'Crisp',
    category: 'basic',
    cssFilter: 'contrast(1.3) brightness(1.02) saturate(1.2)',
    previewGradient: 'linear-gradient(135deg, #10b981, #059669)',
  },

  // ==================== 🎞️ VINTAGE FILTERS ====================
  {
    id: 'vintage',
    name: 'Vintage',
    category: 'vintage',
    cssFilter: 'sepia(0.4) contrast(1.1) brightness(0.95) saturate(1.1)',
    overlayColor: 'rgba(217, 119, 6, 0.15)',
    blendMode: 'multiply',
    previewGradient: 'linear-gradient(135deg, #d97706, #b45309)',
  },
  {
    id: 'retro',
    name: 'Retro',
    category: 'vintage',
    cssFilter: 'sepia(0.3) saturate(1.4) hue-rotate(-15deg) contrast(1.15)',
    previewGradient: 'linear-gradient(135deg, #ea580c, #c2410c)',
  },
  {
    id: '90s',
    name: '90s',
    category: 'vintage',
    cssFilter: 'contrast(1.1) brightness(1.15) saturate(1.3) hue-rotate(5deg)',
    overlayColor: 'rgba(236, 72, 153, 0.1)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #f43f5e, #e11d48)',
  },
  {
    id: '80s',
    name: '80s',
    category: 'vintage',
    cssFilter: 'contrast(1.2) brightness(1.05) saturate(1.6) hue-rotate(-20deg)',
    previewGradient: 'linear-gradient(135deg, #a855f7, #ec4899)',
  },
  {
    id: 'film',
    name: 'Film',
    category: 'vintage',
    cssFilter: 'contrast(1.12) brightness(0.96) saturate(1.08) sepia(0.18)',
    previewGradient: 'linear-gradient(135deg, #713f12, #a16207)',
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    category: 'vintage',
    cssFilter: 'contrast(1.08) brightness(1.1) saturate(1.15) sepia(0.2)',
    overlayColor: 'rgba(254, 240, 138, 0.15)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #fde68a, #f59e0b)',
  },
  {
    id: 'old-camera',
    name: 'Old Camera',
    category: 'vintage',
    cssFilter: 'sepia(0.55) contrast(1.2) brightness(0.9) saturate(0.8)',
    previewGradient: 'linear-gradient(135deg, #854d0e, #582f0e)',
  },
  {
    id: 'faded-film',
    name: 'Faded Film',
    category: 'vintage',
    cssFilter: 'contrast(0.88) brightness(1.12) saturate(0.8) sepia(0.25)',
    previewGradient: 'linear-gradient(135deg, #d6d3d1, #a8a29e)',
  },
  {
    id: 'disposable-camera',
    name: 'Disposable Camera',
    category: 'vintage',
    cssFilter: 'contrast(1.3) brightness(1.15) saturate(1.25) hue-rotate(-10deg)',
    previewGradient: 'linear-gradient(135deg, #22c55e, #15803d)',
  },
  {
    id: 'vhs',
    name: 'VHS',
    category: 'vintage',
    cssFilter: 'contrast(1.2) brightness(1.1) saturate(1.4) hue-rotate(18deg)',
    overlayColor: 'rgba(0, 255, 255, 0.1)',
    blendMode: 'color-dodge',
    previewGradient: 'linear-gradient(135deg, #06b6d4, #8b5cf6)',
  },
  {
    id: 'kodak-style',
    name: 'Kodak-style',
    category: 'vintage',
    cssFilter: 'contrast(1.2) saturate(1.35) sepia(0.15) brightness(1.02)',
    overlayColor: 'rgba(245, 158, 11, 0.12)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #eab308, #ca8a04)',
  },
  {
    id: 'sepia',
    name: 'Sepia',
    category: 'vintage',
    cssFilter: 'sepia(0.85) contrast(1.05) brightness(0.95)',
    previewGradient: 'linear-gradient(135deg, #92400e, #78350f)',
  },

  // ==================== 🖤 BLACK & WHITE ====================
  {
    id: 'classic-bw',
    name: 'Classic B&W',
    category: 'bw',
    cssFilter: 'grayscale(1) contrast(1.15)',
    previewGradient: 'linear-gradient(135deg, #475569, #1e293b)',
  },
  {
    id: 'high-contrast-bw',
    name: 'High Contrast B&W',
    category: 'bw',
    cssFilter: 'grayscale(1) contrast(1.6) brightness(1.05)',
    previewGradient: 'linear-gradient(135deg, #0f172a, #000000)',
  },
  {
    id: 'soft-bw',
    name: 'Soft B&W',
    category: 'bw',
    cssFilter: 'grayscale(1) contrast(0.9) brightness(1.15)',
    previewGradient: 'linear-gradient(135deg, #94a3b8, #64748b)',
  },
  {
    id: 'noir',
    name: 'Noir',
    category: 'bw',
    cssFilter: 'grayscale(1) contrast(1.8) brightness(0.85)',
    previewGradient: 'linear-gradient(135deg, #020617, #1e1b4b)',
  },
  {
    id: 'dramatic-bw',
    name: 'Dramatic',
    category: 'bw',
    cssFilter: 'grayscale(1) contrast(1.45) brightness(0.95)',
    previewGradient: 'linear-gradient(135deg, #334155, #1e293b)',
  },
  {
    id: 'newspaper',
    name: 'Newspaper',
    category: 'bw',
    cssFilter: 'grayscale(1) contrast(1.3) brightness(1.08) sepia(0.1)',
    previewGradient: 'linear-gradient(135deg, #e2e8f0, #475569)',
  },
  {
    id: 'silver',
    name: 'Silver',
    category: 'bw',
    cssFilter: 'grayscale(1) brightness(1.2) contrast(1.1)',
    previewGradient: 'linear-gradient(135deg, #f1f5f9, #94a3b8)',
  },

  // ==================== 💕 CUTE / AESTHETIC ====================
  {
    id: 'pink-glow',
    name: 'Pink Glow',
    category: 'aesthetic',
    cssFilter: 'brightness(1.1) saturate(1.3) contrast(1.05)',
    overlayColor: 'rgba(244, 114, 182, 0.25)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #f472b6, #ec4899)',
  },
  {
    id: 'dreamy',
    name: 'Dreamy',
    category: 'aesthetic',
    cssFilter: 'brightness(1.15) contrast(0.9) saturate(1.2) blur(0.2px)',
    overlayColor: 'rgba(232, 121, 249, 0.18)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #e879f9, #c084fc)',
  },
  {
    id: 'soft-pink',
    name: 'Soft Pink',
    category: 'aesthetic',
    cssFilter: 'brightness(1.08) contrast(0.98) saturate(1.15)',
    overlayColor: 'rgba(251, 207, 232, 0.28)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #fbcfe8, #f472b6)',
  },
  {
    id: 'pastel',
    name: 'Pastel',
    category: 'aesthetic',
    cssFilter: 'contrast(0.9) brightness(1.12) saturate(1.1)',
    overlayColor: 'rgba(199, 210, 254, 0.2)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #c7d2fe, #fbcfe8)',
  },
  {
    id: 'peach',
    name: 'Peach',
    category: 'aesthetic',
    cssFilter: 'brightness(1.08) saturate(1.25) contrast(1.02) hue-rotate(-8deg)',
    overlayColor: 'rgba(254, 215, 170, 0.28)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #fed7aa, #fb923c)',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    category: 'aesthetic',
    cssFilter: 'brightness(1.06) saturate(1.15) hue-rotate(10deg)',
    overlayColor: 'rgba(221, 214, 254, 0.25)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #ddd6fe, #a78bfa)',
  },
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    category: 'aesthetic',
    cssFilter: 'contrast(1.1) brightness(1.12) saturate(1.45)',
    overlayColor: 'rgba(244, 63, 94, 0.2)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #f43f5e, #fb7185)',
  },
  {
    id: 'sweet',
    name: 'Sweet',
    category: 'aesthetic',
    cssFilter: 'brightness(1.1) saturate(1.2) contrast(0.95)',
    overlayColor: 'rgba(253, 164, 175, 0.22)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #fda4af, #f43f5e)',
  },
  {
    id: 'angel',
    name: 'Angel',
    category: 'aesthetic',
    cssFilter: 'brightness(1.22) contrast(0.92) saturate(1.08)',
    overlayColor: 'rgba(255, 255, 255, 0.3)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #ffffff, #e0e7ff)',
  },
  {
    id: 'cloudy',
    name: 'Cloudy',
    category: 'aesthetic',
    cssFilter: 'contrast(0.92) brightness(1.08) saturate(0.95) hue-rotate(12deg)',
    previewGradient: 'linear-gradient(135deg, #e0f2fe, #bae6fd)',
  },
  {
    id: 'romantic',
    name: 'Romantic',
    category: 'aesthetic',
    cssFilter: 'sepia(0.2) brightness(1.06) saturate(1.2) contrast(1.05)',
    overlayColor: 'rgba(244, 114, 182, 0.18)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #f472b6, #fb7185)',
  },
  {
    id: 'kawaii',
    name: 'Kawaii',
    category: 'aesthetic',
    cssFilter: 'brightness(1.16) contrast(1.08) saturate(1.4)',
    overlayColor: 'rgba(251, 113, 133, 0.22)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #fb7185, #f472b6)',
  },

  // ==================== ✨ GLOW EFFECTS ====================
  {
    id: 'golden-glow',
    name: 'Golden Glow',
    category: 'glow',
    cssFilter: 'brightness(1.14) contrast(1.1) saturate(1.3) sepia(0.2)',
    overlayColor: 'rgba(251, 191, 36, 0.28)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
  },
  {
    id: 'sunset',
    name: 'Sunset',
    category: 'glow',
    cssFilter: 'contrast(1.15) brightness(1.05) saturate(1.4) hue-rotate(-15deg)',
    overlayColor: 'rgba(249, 115, 22, 0.24)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #f97316, #ec4899)',
  },
  {
    id: 'neon',
    name: 'Neon',
    category: 'glow',
    cssFilter: 'contrast(1.35) brightness(1.1) saturate(1.8) hue-rotate(20deg)',
    overlayColor: 'rgba(168, 85, 247, 0.25)',
    blendMode: 'color-dodge',
    previewGradient: 'linear-gradient(135deg, #a855f7, #06b6d4)',
  },
  {
    id: 'blue-glow',
    name: 'Blue Glow',
    category: 'glow',
    cssFilter: 'brightness(1.1) contrast(1.1) saturate(1.25) hue-rotate(15deg)',
    overlayColor: 'rgba(56, 189, 248, 0.28)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #38bdf8, #2563eb)',
  },
  {
    id: 'purple-glow',
    name: 'Purple Glow',
    category: 'glow',
    cssFilter: 'brightness(1.12) contrast(1.1) saturate(1.35) hue-rotate(35deg)',
    overlayColor: 'rgba(192, 132, 252, 0.28)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #c084fc, #9333ea)',
  },
  {
    id: 'pink-neon-glow',
    name: 'Pink Glow',
    category: 'glow',
    cssFilter: 'brightness(1.15) contrast(1.15) saturate(1.5)',
    overlayColor: 'rgba(244, 114, 182, 0.32)',
    blendMode: 'color-dodge',
    previewGradient: 'linear-gradient(135deg, #f472b6, #db2777)',
  },
  {
    id: 'rainbow',
    name: 'Rainbow',
    category: 'glow',
    cssFilter: 'contrast(1.2) brightness(1.1) saturate(1.6)',
    overlayColor: 'rgba(236, 72, 153, 0.2)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #ef4444, #eab308, #22c55e, #3b82f6, #a855f7)',
  },
  {
    id: 'sparkle-glow',
    name: 'Sparkle',
    category: 'glow',
    cssFilter: 'brightness(1.2) contrast(1.2) saturate(1.3)',
    overlayColor: 'rgba(255, 255, 255, 0.25)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #fef08a, #ffffff)',
  },
  {
    id: 'dream-glow',
    name: 'Dream Glow',
    category: 'glow',
    cssFilter: 'brightness(1.2) contrast(0.95) saturate(1.35) blur(0.3px)',
    overlayColor: 'rgba(244, 114, 182, 0.25)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #f472b6, #67e8f9)',
  },
  {
    id: 'light-leak',
    name: 'Light Leak',
    category: 'glow',
    cssFilter: 'brightness(1.12) contrast(1.05) saturate(1.25)',
    overlayColor: 'rgba(251, 146, 60, 0.3)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #fb923c, #f43f5e)',
  },

  // ==================== 🎬 CINEMATIC ====================
  {
    id: 'cinema',
    name: 'Cinema',
    category: 'cinematic',
    cssFilter: 'contrast(1.25) brightness(0.96) saturate(1.15) sepia(0.12)',
    previewGradient: 'linear-gradient(135deg, #0f172a, #334155)',
  },
  {
    id: 'hollywood',
    name: 'Hollywood',
    category: 'cinematic',
    cssFilter: 'contrast(1.3) brightness(1.05) saturate(1.2) sepia(0.18)',
    overlayColor: 'rgba(245, 158, 11, 0.15)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #b45309, #d97706)',
  },
  {
    id: 'dark-cinema',
    name: 'Dark Cinema',
    category: 'cinematic',
    cssFilter: 'contrast(1.4) brightness(0.85) saturate(1.1)',
    previewGradient: 'linear-gradient(135deg, #030712, #111827)',
  },
  {
    id: 'teal-orange',
    name: 'Teal & Orange',
    category: 'cinematic',
    cssFilter: 'contrast(1.3) brightness(1.02) saturate(1.4) hue-rotate(-10deg)',
    overlayColor: 'rgba(13, 148, 136, 0.18)',
    blendMode: 'screen',
    previewGradient: 'linear-gradient(135deg, #0d9488, #ea580c)',
  },
  {
    id: 'moody',
    name: 'Moody',
    category: 'cinematic',
    cssFilter: 'contrast(1.28) brightness(0.88) saturate(0.9) hue-rotate(5deg)',
    previewGradient: 'linear-gradient(135deg, #1e1b4b, #312e81)',
  },
  {
    id: 'dramatic-film',
    name: 'Dramatic Film',
    category: 'cinematic',
    cssFilter: 'contrast(1.45) brightness(0.92) saturate(1.2)',
    previewGradient: 'linear-gradient(135deg, #18181b, #27272a)',
  },
  {
    id: 'movie-night',
    name: 'Movie Night',
    category: 'cinematic',
    cssFilter: 'contrast(1.2) brightness(0.94) saturate(1.2) sepia(0.1)',
    overlayColor: 'rgba(30, 58, 138, 0.2)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #1e3a8a, #172554)',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    category: 'cinematic',
    cssFilter: 'contrast(1.45) brightness(1.05) saturate(1.7) hue-rotate(45deg)',
    overlayColor: 'rgba(236, 72, 153, 0.25)',
    blendMode: 'color-dodge',
    previewGradient: 'linear-gradient(135deg, #06b6d4, #ec4899)',
  },

  // ==================== 📱 SOCIAL MEDIA ====================
  {
    id: 'instagram-style',
    name: 'Instagram-style',
    category: 'social',
    cssFilter: 'contrast(1.18) brightness(1.08) saturate(1.35)',
    overlayColor: 'rgba(244, 63, 94, 0.12)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #f59e0b, #ec4899, #8b5cf6)',
  },
  {
    id: 'tiktok-style',
    name: 'TikTok-style',
    category: 'social',
    cssFilter: 'contrast(1.25) brightness(1.12) saturate(1.4)',
    previewGradient: 'linear-gradient(135deg, #00f2fe, #4facfe)',
  },
  {
    id: 'selfie',
    name: 'Selfie',
    category: 'social',
    cssFilter: 'brightness(1.15) contrast(1.05) saturate(1.2)',
    overlayColor: 'rgba(254, 205, 211, 0.18)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #fecdd3, #f43f5e)',
  },
  {
    id: 'influencer',
    name: 'Influencer',
    category: 'social',
    cssFilter: 'contrast(1.1) brightness(1.18) saturate(1.25) sepia(0.08)',
    overlayColor: 'rgba(254, 243, 199, 0.2)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #fef3c7, #f59e0b)',
  },
  {
    id: 'clean',
    name: 'Clean',
    category: 'social',
    cssFilter: 'contrast(1.08) brightness(1.06) saturate(1.05)',
    previewGradient: 'linear-gradient(135deg, #f8fafc, #e2e8f0)',
  },
  {
    id: 'aesthetic-feed',
    name: 'Aesthetic',
    category: 'social',
    cssFilter: 'contrast(0.95) brightness(1.1) saturate(1.15) sepia(0.12)',
    overlayColor: 'rgba(251, 146, 60, 0.1)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #fdba74, #f472b6)',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    category: 'social',
    cssFilter: 'contrast(1.04) brightness(1.02) saturate(0.92)',
    previewGradient: 'linear-gradient(135deg, #64748b, #475569)',
  },
  {
    id: 'trending',
    name: 'Trending',
    category: 'social',
    cssFilter: 'contrast(1.22) brightness(1.1) saturate(1.42)',
    overlayColor: 'rgba(168, 85, 247, 0.15)',
    blendMode: 'soft-light',
    previewGradient: 'linear-gradient(135deg, #a855f7, #ec4899)',
  },

  // ==================== 😂 FUN FILTERS ====================
  {
    id: 'big-head',
    name: 'Big Head',
    category: 'fun',
    funEffect: 'bighead',
    cssFilter: 'saturate(1.2)',
    previewGradient: 'linear-gradient(135deg, #facc15, #ca8a04)',
  },
  {
    id: 'small-face',
    name: 'Small Face',
    category: 'fun',
    funEffect: 'smallface',
    cssFilter: 'saturate(1.15)',
    previewGradient: 'linear-gradient(135deg, #38bdf8, #0284c7)',
  },
  {
    id: 'funny-face',
    name: 'Funny Face',
    category: 'fun',
    funEffect: 'wave',
    cssFilter: 'contrast(1.2) saturate(1.3)',
    previewGradient: 'linear-gradient(135deg, #ec4899, #f97316)',
  },
  {
    id: 'cartoon',
    name: 'Cartoon',
    category: 'fun',
    funEffect: 'cartoon',
    cssFilter: 'contrast(1.6) saturate(1.8) brightness(1.05)',
    previewGradient: 'linear-gradient(135deg, #10b981, #3b82f6)',
  },
  {
    id: 'pixel',
    name: 'Pixel',
    category: 'fun',
    funEffect: 'pixelate',
    cssFilter: 'contrast(1.25) saturate(1.4)',
    previewGradient: 'linear-gradient(135deg, #8b5cf6, #6366f1)',
  },
  {
    id: 'fish-eye',
    name: 'Fish Eye',
    category: 'fun',
    funEffect: 'fisheye',
    cssFilter: 'contrast(1.1) saturate(1.2)',
    previewGradient: 'linear-gradient(135deg, #06b6d4, #0891b2)',
  },
  {
    id: 'mirror',
    name: 'Mirror',
    category: 'fun',
    funEffect: 'mirror',
    cssFilter: 'none',
    previewGradient: 'linear-gradient(135deg, #64748b, #cbd5e1)',
  },
  {
    id: 'kaleidoscope',
    name: 'Kaleidoscope',
    category: 'fun',
    funEffect: 'kaleidoscope',
    cssFilter: 'saturate(1.35) contrast(1.15)',
    previewGradient: 'linear-gradient(135deg, #f43f5e, #8b5cf6, #06b6d4)',
  },
  {
    id: 'face-warp',
    name: 'Face Warp',
    category: 'fun',
    funEffect: 'wave',
    cssFilter: 'hue-rotate(25deg) saturate(1.3)',
    previewGradient: 'linear-gradient(135deg, #e11d48, #be185d)',
  },
  {
    id: 'distortion',
    name: 'Distortion',
    category: 'fun',
    funEffect: 'wave',
    cssFilter: 'invert(0.15) contrast(1.4) saturate(1.5)',
    previewGradient: 'linear-gradient(135deg, #4f46e5, #4338ca)',
  },
];
