import { BackgroundOption, FrameStyle } from '../types';

export const FRAMES: FrameStyle[] = [
  {
    id: 'classic',
    name: 'Classic White',
    styleName: 'classic',
    borderWidth: 16,
    padding: 12,
    borderColor: '#ffffff',
    borderRadius: 8,
  },
  {
    id: 'polaroid',
    name: 'Polaroid Style',
    styleName: 'polaroid',
    borderWidth: 14,
    padding: 10,
    borderColor: '#fdfbf7',
    borderRadius: 4,
  },
  {
    id: 'film',
    name: '35mm Film',
    styleName: 'film',
    borderWidth: 20,
    padding: 14,
    borderColor: '#0a0a0c',
    borderRadius: 6,
  },
  {
    id: 'retro',
    name: 'Retro 80s',
    styleName: 'retro',
    borderWidth: 14,
    padding: 10,
    borderColor: '#fb7185',
    borderRadius: 16,
  },
  {
    id: 'neon',
    name: 'Neon Cyber',
    styleName: 'neon',
    borderWidth: 12,
    padding: 8,
    borderColor: '#06b6d4',
    borderRadius: 12,
  },
  {
    id: 'heart',
    name: 'Sweet Heart',
    styleName: 'heart',
    borderWidth: 16,
    padding: 12,
    borderColor: '#f472b6',
    borderRadius: 24,
  },
  {
    id: 'flower',
    name: 'Floral Romance',
    styleName: 'flower',
    borderWidth: 14,
    padding: 12,
    borderColor: '#fed7aa',
    borderRadius: 14,
  },
  {
    id: 'minimal',
    name: 'Minimal Black',
    styleName: 'minimal',
    borderWidth: 8,
    padding: 8,
    borderColor: '#18181b',
    borderRadius: 2,
  },
  {
    id: 'birthday',
    name: 'Birthday Party',
    styleName: 'birthday',
    borderWidth: 18,
    padding: 12,
    borderColor: '#fde047',
    borderRadius: 20,
  },
  {
    id: 'wedding',
    name: 'Wedding Elegance',
    styleName: 'wedding',
    borderWidth: 16,
    padding: 14,
    borderColor: '#fef3c7',
    borderRadius: 10,
  },
  {
    id: 'christmas',
    name: 'Holiday Christmas',
    styleName: 'christmas',
    borderWidth: 16,
    padding: 12,
    borderColor: '#dc2626',
    borderRadius: 12,
  },
  {
    id: 'halloween',
    name: 'Spooky Halloween',
    styleName: 'halloween',
    borderWidth: 16,
    padding: 12,
    borderColor: '#ea580c',
    borderRadius: 10,
  },
];

export const BACKGROUNDS: BackgroundOption[] = [
  { id: 'white', name: 'Clean White', type: 'solid', value: '#ffffff' },
  { id: 'cream', name: 'Warm Cream', type: 'solid', value: '#fdfbf7' },
  { id: 'black', name: 'Midnight Black', type: 'solid', value: '#0f172a' },
  { id: 'pastel-pink', name: 'Pastel Pink', type: 'solid', value: '#fce7f3' },
  { id: 'pastel-blue', name: 'Pastel Blue', type: 'solid', value: '#e0f2fe' },
  { id: 'pastel-purple', name: 'Pastel Lavender', type: 'solid', value: '#f3e8ff' },
  { id: 'pastel-mint', name: 'Pastel Mint', type: 'solid', value: '#dcfce7' },
  { id: 'pastel-peach', name: 'Pastel Peach', type: 'solid', value: '#ffedd5' },

  // Gradients
  {
    id: 'grad-sunset',
    name: 'Sunset Glow',
    type: 'gradient',
    value: 'linear-gradient(135deg, #f43f5e, #fb923c)',
  },
  {
    id: 'grad-cyber',
    name: 'Cyberpunk',
    type: 'gradient',
    value: 'linear-gradient(135deg, #06b6d4, #a855f7)',
  },
  {
    id: 'grad-cotton-candy',
    name: 'Cotton Candy',
    type: 'gradient',
    value: 'linear-gradient(135deg, #fbcfe8, #c7d2fe)',
  },
  {
    id: 'grad-aurora',
    name: 'Northern Aurora',
    type: 'gradient',
    value: 'linear-gradient(135deg, #10b981, #06b6d4)',
  },
  {
    id: 'grad-dark-luxury',
    name: 'Dark Gold',
    type: 'gradient',
    value: 'linear-gradient(135deg, #18181b, #27272a, #854d0e)',
  },
  {
    id: 'grad-bubblegum',
    name: 'Bubblegum',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ec4899, #f43f5e)',
  },

  // Patterns
  {
    id: 'pattern-dots',
    name: 'Polka Dots',
    type: 'pattern',
    value: 'radial-gradient(#ec4899 15%, transparent 16%), radial-gradient(#ec4899 15%, transparent 16%)',
  },
  {
    id: 'pattern-checker',
    name: 'Checkered',
    type: 'pattern',
    value: 'linear-gradient(45deg, #f1f5f9 25%, transparent 25%), linear-gradient(-45deg, #f1f5f9 25%, transparent 25%)',
  },
];
